---

- name: Install Packages
  hosts: 
  - workstation
  become: true
  remote_user: kenny
 
  pre_tasks: 
    - name: Update all repositories
      apt: 
       update_cache: yes 

    - name: Upgrade all packages
      apt: 
        name: "*" 
        state: latest
  
  tasks:
    - name: Installing dnf packages 
      package: 
        name: 
          - snapd
          - git
          - google-chrome-stable
          - cifs-utils
          - unzip
          - ack
          - fzf

    - name: installing snap packages
      snap: 
        name: 
          - spotify
