---

- name: Install Brew Packages
  hosts: localhost
  become: false
  vars: 
    # brew_cask_packages: 
    brew_packages: 
     # - leapp # currently not working on linux
      - k9s
        #- leapp
      - helm
      - kubectl
      - hashicorp/tap/terraform-ls
      - tflint
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check
    
    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
  tasks: 
    - name: Tap HashiCorp
      homebrew_tap:
        name: hashicorp/tap
        state: present

    - name: Install terraform-ls
      homebrew:
        name: terraform-ls
        state: present

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

