---

- name: Vim Customization and Config
  hosts: 
  - localhost
  connection: local
  become: false
  vars:
    home_dir: "{{ ansible_facts['env']['HOME'] }}"
    repo_root: "{{ ansible_facts['env']['HOME'] }}/src"
 
  tasks:
    - name: check if homebrew is installed
      command: brew --prefix
      register: brew_prefix
      changed_when: false
      failed_when: false

    - name: install neovim lint tools with homebrew
      homebrew:
        name:
          - hadolint
          - golangci-lint
          - ruff
        state: present
      when: brew_prefix.rc == 0

    - name: create directory for neovim config
      file: 
        path: "{{ home_dir }}/.config/nvim/"
        state: directory
        mode: '0755'
    - name: create directory for lazy lua config
      file: 
        path: "{{ home_dir }}/.config/nvim/lua/config/"
        state: directory
        mode: '0755'
    - name: create directory for vim plugin pack
      file:
        path: "{{ home_dir }}/.vim/pack/plugins/start/"
        state: directory
        mode: '0755'
    - name: copy init.lua file
      copy:
        src: "{{ repo_root }}/dotfiles/init.lua"
        dest: "{{ home_dir }}/.config/nvim/init.lua"
    - name: copy plugins.lua file
      copy: 
        src: "{{ repo_root }}/dotfiles/lua/config/plugins.lua"
        dest: "{{ home_dir }}/.config/nvim/lua/config/plugins.lua"

    - name: copy lazy.lua
      copy: 
        src: "{{ repo_root }}/dotfiles/lua/config/lazy.lua"
        dest: "{{ home_dir }}/.config/nvim/lua/config/lazy.lua"
    - name: clone repo for vim-terraform
      git:
        repo: 'https://github.com/hashivim/vim-terraform.git'
        dest: "{{ home_dir }}/.vim/pack/plugins/start/vim-terraform"
        clone: yes
        update: no
